# Download latest ubuntu base image
FROM ubuntu:latest

LABEL maintainer="rayyl@yahoo.com"

#
# Update the image to the latest package
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y vim

